"""
Report model — AI-generated marketing performance reports.

Reports are generated by the AI pipeline and contain sections,
insights, and recommendations.
"""

import uuid
from datetime import date

from sqlalchemy import Date, ForeignKey, Integer, String, Text, Uuid
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import BaseModel, JSONVariant, SoftDeleteMixin


class Report(BaseModel, SoftDeleteMixin):
    """
    An AI-generated marketing performance report.

    Contains metadata about the report generation, date range,
    and links to its sections, insights, and recommendations.
    """

    __tablename__ = "reports"

    organization_id: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        ForeignKey("organizations.id"),
        nullable=False,
        index=True,
    )
    generated_by: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        ForeignKey("users.id"),
        nullable=False,
    )
    template: Mapped[str] = mapped_column(
        String(100), default="monthly_performance", nullable=False
    )
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    status: Mapped[str] = mapped_column(
        String(50), default="generating", nullable=False
        # 'generating', 'completed', 'failed'
    )
    date_range_start: Mapped[date] = mapped_column(Date, nullable=False)
    date_range_end: Mapped[date] = mapped_column(Date, nullable=False)
    comparison_period: Mapped[str | None] = mapped_column(
        String(50), nullable=True  # 'previous_period', 'previous_year'
    )
    platforms: Mapped[list] = mapped_column(
        JSONVariant, nullable=False  # List of platform strings
    )
    tone: Mapped[str] = mapped_column(
        String(50), default="executive", nullable=False
    )
    pdf_url: Mapped[str | None] = mapped_column(String(500), nullable=True)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)

    # AI generation metadata
    ai_model: Mapped[str | None] = mapped_column(String(100), nullable=True)
    ai_tokens_used: Mapped[int | None] = mapped_column(Integer, nullable=True)
    generation_time_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # Report content stored as structured JSON
    summary_data: Mapped[dict] = mapped_column(JSONVariant, default=dict, nullable=False)

    # Relationships
    organization: Mapped["Organization"] = relationship(  # noqa: F821
        back_populates="reports",
        lazy="selectin",
    )
    generated_by_user: Mapped["User"] = relationship(  # noqa: F821
        lazy="selectin",
    )
    insights: Mapped[list["Insight"]] = relationship(  # noqa: F821
        back_populates="report",
        lazy="selectin",
        cascade="all, delete-orphan",
    )
    recommendations: Mapped[list["Recommendation"]] = relationship(  # noqa: F821
        back_populates="report",
        lazy="selectin",
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:
        return f"<Report {self.title} ({self.status})>"
